# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='calls_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='five_match_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='group_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='meetings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
