# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20170116_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='winner',
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2_points',
            field=models.IntegerField(default=0),
        ),
    ]
