# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20170116_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
