# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_fixture_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsofuserperfixture',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='pointsofuserperfixture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.DeleteModel(
            name='PointsOfUserPerFixture',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
