# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20170116_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='winner',
            field=models.CharField(default=b'NA', max_length=128),
        ),
    ]
